<?php

$plugin = array(
  'title' => t('Roycemore Blog Teaser'),
  'icon' => 'royce-blog-teaser.png',
  'category' => t('Royce Content'),
  'theme' => 'royce-blog-teaser',
  'regions' => array(
    'content-header' => t('Header'),
    'content-author' => t('Author'),
    'content-date' => t('Date'),
    'content-categories' => t('Categories'),
    'content-social' => t('Social Sharing'),
    'content-teaser' => t('Blog Teaser'),
  ),
);
