<?php

$plugin = array(
  'title' => t('Roycemore top + 3 grid + bottom'),
  'icon' => 'royce-top-3grid-bottom.png',
  'category' => t('Royce'),
  'theme' => 'royce-top-3grid-bottom',
  'regions' => array(
    'content-section' => t('Content'),
    'specialitem1' => t('Special Item 1'),
    'specialitem2' => t('Special Item 2'),
    'specialitem3' => t('Special Item 3'),
    'content-bottom-section' => t('Bottom Content'),
  ),
);
