<?php

$plugin = array(
  'title' => t('Homepage'),
  'icon' => 'royce-homepage.png',
  'category' => t('Royce'),
  'theme' => 'royce-homepage',
  'regions' => array(
    'header' => t('Header'),
    'aboutroycemore' => t('About Roycemore'),
    'searchside' => t('Search Side'),
    'update1' => t('Update 1'),
    'update2' => t('Update 2'),
    'update3' => t('Update 3'),
    'update4' => t('Update 4'),
    'specialitem1' => t('Third Item 1'),
    'specialitem2' => t('Third Item 2'),
    'specialitem3' => t('Third Item 3'),
    'video1' => t('video 1'),
    'video2' => t('video 2'),
    'video3' => t('video 3'),
    'video4' => t('video 4'),
    'map' => t('Map'),
  ),
);
