<?php

$plugin = array(
  'title' => t('Roycemore Content Header + Left Content Section with 3 grid + Right Aside'),
  'icon' => 'royce-top-content-3grid-left.png',
  'category' => t('Royce'),
  'theme' => 'royce-top-content-3grid-left',
  'regions' => array(
    'content-header' => t('Content Header'),
    'content-section' => t('Content'),
    'specialitem1' => t('Special Item 1'),
    'specialitem2' => t('Special Item 2'),
    'specialitem3' => t('Special Item 3'),
    'content-bottom-section' => t('Bottom Content'),
    'content-aside' => t('Aside'),
  ),
);
